enum TrainingLevelType {
  consecutiveMakes,
  targetMakes,
  freeThrows,
  mixedSpots,
  timed,
}

class TrainingLevel {
  const TrainingLevel({
    required this.number,
    required this.title,
    required this.description,
    required this.type,
    required this.targetMakes,
    required this.attemptLimit,
    required this.requiredStreak,
    required this.threeStarMisses,
    required this.twoStarMisses,
    this.timeLimitSeconds,
  });

  final int number;
  final String title;
  final String description;
  final TrainingLevelType type;
  final int targetMakes;
  final int attemptLimit;
  final int requiredStreak;
  final int threeStarMisses;
  final int twoStarMisses;
  final int? timeLimitSeconds;

  LevelResult score({
    required int makes,
    required int misses,
    required int bestStreak,
  }) {
    final attempts = makes + misses;
    if (makes < targetMakes || bestStreak < requiredStreak) {
      return LevelResult.failed(attempts: attempts);
    }

    final stars = misses <= threeStarMisses
        ? 3
        : misses <= twoStarMisses
        ? 2
        : 1;
    return LevelResult(
      passed: true,
      stars: stars,
      makes: makes,
      misses: misses,
      bestStreak: bestStreak,
      attempts: attempts,
    );
  }
}

class LevelResult {
  const LevelResult({
    required this.passed,
    required this.stars,
    required this.makes,
    required this.misses,
    required this.bestStreak,
    required this.attempts,
  });

  const LevelResult.failed({required this.attempts})
    : passed = false,
      stars = 0,
      makes = 0,
      misses = 0,
      bestStreak = 0;

  final bool passed;
  final int stars;
  final int makes;
  final int misses;
  final int bestStreak;
  final int attempts;
}

const levelCatalog = <TrainingLevel>[
  TrainingLevel(
    number: 1,
    title: 'Layup Ladder',
    description: 'Make 3 layups in a row.',
    type: TrainingLevelType.consecutiveMakes,
    targetMakes: 3,
    attemptLimit: 10,
    requiredStreak: 3,
    threeStarMisses: 0,
    twoStarMisses: 2,
  ),
  TrainingLevel(
    number: 2,
    title: 'Right-Hand Rhythm',
    description: 'Make 4 right-hand layups.',
    type: TrainingLevelType.targetMakes,
    targetMakes: 4,
    attemptLimit: 10,
    requiredStreak: 2,
    threeStarMisses: 0,
    twoStarMisses: 2,
  ),
  TrainingLevel(
    number: 3,
    title: 'Left-Hand Rhythm',
    description: 'Make 4 left-hand layups.',
    type: TrainingLevelType.targetMakes,
    targetMakes: 4,
    attemptLimit: 10,
    requiredStreak: 2,
    threeStarMisses: 0,
    twoStarMisses: 2,
  ),
  TrainingLevel(
    number: 4,
    title: 'Paint Touches',
    description: 'Make 5 shots from the paint.',
    type: TrainingLevelType.targetMakes,
    targetMakes: 5,
    attemptLimit: 12,
    requiredStreak: 2,
    threeStarMisses: 0,
    twoStarMisses: 2,
  ),
  TrainingLevel(
    number: 5,
    title: 'Corner Starter',
    description: 'Make 5 corner shots.',
    type: TrainingLevelType.targetMakes,
    targetMakes: 5,
    attemptLimit: 12,
    requiredStreak: 3,
    threeStarMisses: 0,
    twoStarMisses: 2,
  ),
  TrainingLevel(
    number: 6,
    title: 'Elbow Check',
    description: 'Make 5 elbow jumpers.',
    type: TrainingLevelType.targetMakes,
    targetMakes: 5,
    attemptLimit: 12,
    requiredStreak: 3,
    threeStarMisses: 0,
    twoStarMisses: 2,
  ),
  TrainingLevel(
    number: 7,
    title: 'Two-Spot Sweep',
    description: 'Make 6 shots from two marked spots.',
    type: TrainingLevelType.mixedSpots,
    targetMakes: 6,
    attemptLimit: 14,
    requiredStreak: 3,
    threeStarMisses: 1,
    twoStarMisses: 3,
  ),
  TrainingLevel(
    number: 8,
    title: 'Arc Builder',
    description: 'Make 6 three-pointers.',
    type: TrainingLevelType.targetMakes,
    targetMakes: 6,
    attemptLimit: 15,
    requiredStreak: 3,
    threeStarMisses: 1,
    twoStarMisses: 3,
  ),
  TrainingLevel(
    number: 9,
    title: 'Recovery Run',
    description: 'Make 6 shots with no more than 3 misses.',
    type: TrainingLevelType.targetMakes,
    targetMakes: 6,
    attemptLimit: 14,
    requiredStreak: 2,
    threeStarMisses: 1,
    twoStarMisses: 3,
  ),
  TrainingLevel(
    number: 10,
    title: 'Free-Throw Five',
    description: 'Make 5 free throws in a row.',
    type: TrainingLevelType.freeThrows,
    targetMakes: 5,
    attemptLimit: 12,
    requiredStreak: 5,
    threeStarMisses: 0,
    twoStarMisses: 2,
  ),
  TrainingLevel(
    number: 11,
    title: 'Free-Throw Flow',
    description: 'Make 7 free throws.',
    type: TrainingLevelType.freeThrows,
    targetMakes: 7,
    attemptLimit: 14,
    requiredStreak: 4,
    threeStarMisses: 0,
    twoStarMisses: 2,
  ),
  TrainingLevel(
    number: 12,
    title: 'Baseline Pair',
    description: 'Make 6 baseline jumpers.',
    type: TrainingLevelType.targetMakes,
    targetMakes: 6,
    attemptLimit: 14,
    requiredStreak: 3,
    threeStarMisses: 1,
    twoStarMisses: 3,
  ),
  TrainingLevel(
    number: 13,
    title: 'Midrange Meter',
    description: 'Make 8 midrange shots.',
    type: TrainingLevelType.targetMakes,
    targetMakes: 8,
    attemptLimit: 18,
    requiredStreak: 4,
    threeStarMisses: 1,
    twoStarMisses: 4,
  ),
  TrainingLevel(
    number: 14,
    title: 'Five-Spot Circuit',
    description: 'Make 8 shots across five spots.',
    type: TrainingLevelType.mixedSpots,
    targetMakes: 8,
    attemptLimit: 18,
    requiredStreak: 4,
    threeStarMisses: 1,
    twoStarMisses: 4,
  ),
  TrainingLevel(
    number: 15,
    title: 'Deep Water',
    description: 'Make 7 threes from the arc.',
    type: TrainingLevelType.targetMakes,
    targetMakes: 7,
    attemptLimit: 18,
    requiredStreak: 4,
    threeStarMisses: 1,
    twoStarMisses: 4,
  ),
  TrainingLevel(
    number: 16,
    title: 'Alternating Hands',
    description: 'Make 8 alternating-hand finishes.',
    type: TrainingLevelType.mixedSpots,
    targetMakes: 8,
    attemptLimit: 18,
    requiredStreak: 4,
    threeStarMisses: 1,
    twoStarMisses: 4,
  ),
  TrainingLevel(
    number: 17,
    title: 'Free-Throw Pressure',
    description: 'Make 8 free throws with a streak of 5.',
    type: TrainingLevelType.freeThrows,
    targetMakes: 8,
    attemptLimit: 18,
    requiredStreak: 5,
    threeStarMisses: 1,
    twoStarMisses: 4,
  ),
  TrainingLevel(
    number: 18,
    title: 'Closeout Read',
    description: 'Make 9 shots after changing spots.',
    type: TrainingLevelType.mixedSpots,
    targetMakes: 9,
    attemptLimit: 20,
    requiredStreak: 4,
    threeStarMisses: 1,
    twoStarMisses: 4,
  ),
  TrainingLevel(
    number: 19,
    title: 'Arc and Paint',
    description: 'Make 10 shots split between threes and finishes.',
    type: TrainingLevelType.mixedSpots,
    targetMakes: 10,
    attemptLimit: 22,
    requiredStreak: 5,
    threeStarMisses: 2,
    twoStarMisses: 5,
  ),
  TrainingLevel(
    number: 20,
    title: 'Timed Ten',
    description: 'Make 10 shots in 90 seconds.',
    type: TrainingLevelType.timed,
    targetMakes: 10,
    attemptLimit: 22,
    requiredStreak: 5,
    threeStarMisses: 2,
    twoStarMisses: 5,
    timeLimitSeconds: 90,
  ),
  TrainingLevel(
    number: 21,
    title: 'Corner to Corner',
    description: 'Make 10 shots from alternating corners.',
    type: TrainingLevelType.mixedSpots,
    targetMakes: 10,
    attemptLimit: 22,
    requiredStreak: 5,
    threeStarMisses: 2,
    twoStarMisses: 5,
  ),
  TrainingLevel(
    number: 22,
    title: 'Free-Throw Ten',
    description: 'Make 10 free throws with a streak of 6.',
    type: TrainingLevelType.freeThrows,
    targetMakes: 10,
    attemptLimit: 24,
    requiredStreak: 6,
    threeStarMisses: 2,
    twoStarMisses: 5,
  ),
  TrainingLevel(
    number: 23,
    title: 'Moving Target',
    description: 'Make 11 shots after every rebound.',
    type: TrainingLevelType.mixedSpots,
    targetMakes: 11,
    attemptLimit: 24,
    requiredStreak: 5,
    threeStarMisses: 2,
    twoStarMisses: 5,
  ),
  TrainingLevel(
    number: 24,
    title: 'Three-Point Route',
    description: 'Make 12 threes from the five-spot route.',
    type: TrainingLevelType.mixedSpots,
    targetMakes: 12,
    attemptLimit: 26,
    requiredStreak: 6,
    threeStarMisses: 2,
    twoStarMisses: 5,
  ),
  TrainingLevel(
    number: 25,
    title: 'Pressure Pair',
    description: 'Make 12 shots, including 6 in a row.',
    type: TrainingLevelType.targetMakes,
    targetMakes: 12,
    attemptLimit: 26,
    requiredStreak: 6,
    threeStarMisses: 2,
    twoStarMisses: 5,
  ),
  TrainingLevel(
    number: 26,
    title: 'Timed Circuit',
    description: 'Make 12 shots in 75 seconds.',
    type: TrainingLevelType.timed,
    targetMakes: 12,
    attemptLimit: 26,
    requiredStreak: 6,
    threeStarMisses: 2,
    twoStarMisses: 5,
    timeLimitSeconds: 75,
  ),
  TrainingLevel(
    number: 27,
    title: 'Full Court Finish',
    description: 'Make 13 alternating finishes.',
    type: TrainingLevelType.mixedSpots,
    targetMakes: 13,
    attemptLimit: 28,
    requiredStreak: 6,
    threeStarMisses: 2,
    twoStarMisses: 6,
  ),
  TrainingLevel(
    number: 28,
    title: 'Free-Throw Marathon',
    description: 'Make 14 free throws with a streak of 7.',
    type: TrainingLevelType.freeThrows,
    targetMakes: 14,
    attemptLimit: 30,
    requiredStreak: 7,
    threeStarMisses: 2,
    twoStarMisses: 6,
  ),
  TrainingLevel(
    number: 29,
    title: 'Complete the Arc',
    description: 'Make 15 shots across every marked spot.',
    type: TrainingLevelType.mixedSpots,
    targetMakes: 15,
    attemptLimit: 32,
    requiredStreak: 7,
    threeStarMisses: 3,
    twoStarMisses: 7,
  ),
  TrainingLevel(
    number: 30,
    title: 'SwishTrace Finale',
    description: 'Make 15 shots in 90 seconds with a streak of 8.',
    type: TrainingLevelType.timed,
    targetMakes: 15,
    attemptLimit: 32,
    requiredStreak: 8,
    threeStarMisses: 3,
    twoStarMisses: 7,
    timeLimitSeconds: 90,
  ),
];
